# Generated by Django 5.2.1 on 2025-05-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
